name: spt
base: core18
version: latest
version-script: git -C parts/spt/build describe --tags | sed 's/v//'
summary: Spotify TUI
description: |
  Spotify for the terminal written in Rust

grade: stable
confinement: strict

parts:
  spotify-tui:
    plugin: rust
    source: https://github.com/Rigellute/spotify-tui.git
    build-packages:
      - libssl-dev
      - pkg-config
      - libxcb1-dev
      - libxcb-render0-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
    stage-packages:
      - libxau6
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xfixes0
      - libxcb1
      - libxdmcp6
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_committed_tag_ver="$(echo ${last_committed_tag} | sed 's/v//')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi

apps:
  spt:
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
    command: spt
    plugs:
      - desktop
      - network
      - network-bind
      - pulseaudio

